#include <stdio.h>
#include "handlers.h"
#include "bytecode.h"
#include "frame.h"
#include "heap.h"
#include "runtime.h"
static void unsupported(const char *name) { fprintf(stderr, "[JVMR/ERROR] %s is unavailable without a class/object runtime.\n", name); }
#define UNSUPPORTED(name) void handler_##name(void) { unsupported(#name); }
void handler_getstatic(void) { uint16_t index=(uint16_t)((fetch_bytecode()<<8)|fetch_bytecode()); const JVMR_Class *klass; const JVMR_Field *field=jvmr_runtime_resolve_field(index,&klass); if(!field||!(field->access_flags&0x0008)){unsupported("getstatic");current_frame.pc=UINT32_MAX;return;} if(jvmr_ensure_initialized(klass)){current_frame.pc=UINT32_MAX;return;} if(!klass->static_values[field->slot]&&field->constant_value_index<klass->constant_pool_count&&klass->constant_pool[field->constant_value_index].tag==JVMR_CP_STRING){const JVMR_Constant *string=&klass->constant_pool[field->constant_value_index];if(string->value.index<klass->constant_pool_count&&klass->constant_pool[string->value.index].tag==JVMR_CP_UTF8){const JVMR_Constant *text=&klass->constant_pool[string->value.index];int reference=jvmr_heap_new_string(text->value.utf8.bytes,text->value.utf8.length,klass);if(reference<0){current_frame.pc=UINT32_MAX;return;}((JVMR_Class *)klass)->static_values[field->slot]=(uint64_t)reference;}} current_frame.stack[current_frame.sp++]=klass->static_values[field->slot]; }
void handler_putstatic(void) { uint16_t index=(uint16_t)((fetch_bytecode()<<8)|fetch_bytecode()); const JVMR_Class *klass; const JVMR_Field *field=jvmr_runtime_resolve_field(index,&klass); if(!field||!(field->access_flags&0x0008)){unsupported("putstatic");current_frame.pc=UINT32_MAX;return;} if(jvmr_ensure_initialized(klass)){current_frame.pc=UINT32_MAX;return;} ((JVMR_Class *)klass)->static_values[field->slot]=current_frame.stack[--current_frame.sp]; }
void handler_getfield(void) { uint16_t index=(uint16_t)((fetch_bytecode()<<8)|fetch_bytecode()); const JVMR_Class *owner=NULL; const JVMR_Field *field=jvmr_runtime_resolve_field(index,&owner); uint64_t ref=current_frame.stack[current_frame.sp-1],value; const JVMR_Class *object_class=jvmr_heap_object_class(ref); int offset=field?jvmr_runtime_field_offset(object_class,owner,field):-1; if(!field||offset<0||jvmr_heap_field_load(ref,(uint16_t)offset,&value)){if(!ref)jvmr_throw_named("java/lang/NullPointerException");else {unsupported("getfield");current_frame.pc=UINT32_MAX;}return;} current_frame.stack[current_frame.sp-1]=value; }
void handler_putfield(void) { uint16_t index=(uint16_t)((fetch_bytecode()<<8)|fetch_bytecode()); const JVMR_Class *owner; const JVMR_Field *field=jvmr_runtime_resolve_field(index,&owner); uint64_t value=current_frame.stack[--current_frame.sp],ref=current_frame.stack[--current_frame.sp]; const JVMR_Class *object_class=jvmr_heap_object_class(ref); int offset=field?jvmr_runtime_field_offset(object_class,owner,field):-1; if(!field||offset<0||jvmr_heap_field_store(ref,(uint16_t)offset,value)){if(!ref)jvmr_throw_named("java/lang/NullPointerException");else {unsupported("putfield");current_frame.pc=UINT32_MAX;}return;} }
