#include <math.h>
#include <stdint.h>
#include <string.h>
#include <time.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <sys/stat.h>
#include <unistd.h>
#include "frame.h"
#include "heap.h"
#include "native.h"
#include "runtime.h"

static int matches(const JVMR_Class *c,const JVMR_Method *m,const char *owner,const char *name,const char *desc){return c&&m&&c->name&&!strcmp(c->name,owner)&&m->name&&!strcmp(m->name,name)&&m->descriptor&&!strcmp(m->descriptor,desc);}
static uint64_t double_value(double value){uint64_t bits;memcpy(&bits,&value,8);return bits;}
static double as_double(uint64_t bits){double value;memcpy(&value,&bits,8);return value;}
static uint32_t float_value(float value){uint32_t bits;memcpy(&bits,&value,4);return bits;}
static float as_float(uint64_t bits){float value;uint32_t compact=(uint32_t)bits;memcpy(&value,&compact,4);return value;}
static int32_t int_arg(int offset){return (int32_t)current_frame.stack[current_frame.sp-offset];}
static uint64_t main_thread_reference;
static uint64_t system_classloader_reference;
static FILE **input_streams;
static size_t input_stream_capacity;
static FILE **output_streams;
static size_t output_stream_capacity;
static const JVMR_Field *field_named(const JVMR_Class *c,const char *name,const char *descriptor){return jvmr_class_find_field(c,name,descriptor);}
static int boxed_value(const JVMR_Class *c,const char *descriptor,uint64_t value){const JVMR_Field *field=field_named(c,"value",descriptor);if(!field)return -1;int reference=jvmr_heap_new_object(c);if(reference<0||jvmr_heap_field_store((uint64_t)reference,field->slot,value))return -1;current_frame.sp--;current_frame.stack[current_frame.sp++]=(uint64_t)reference;return 0;}
static int host_string_result(const char *value){if(!value){current_frame.stack[current_frame.sp-1]=0;return 0;}const JVMR_Class *string_class=jvmr_runtime_load_class_name("java/lang/String");int reference=jvmr_heap_new_string((const uint8_t *)value,(uint16_t)strlen(value),string_class?string_class:jvmr_runtime_class());if(reference<0)return -1;current_frame.stack[current_frame.sp-1]=(uint64_t)reference;return 0;}
static const char *host_property_value(const char *key,int environment){const char *value=NULL;if(environment)value=getenv(key);else if(!strcmp(key,"java.version"))value="21";else if(!strcmp(key,"java.specification.version"))value="21";else if(!strcmp(key,"java.runtime.version"))value="21";else if(!strcmp(key,"java.vendor"))value="OpenJDK";else if(!strcmp(key,"java.vm.name"))value="JVMR";else if(!strcmp(key,"java.home")){value=getenv("JAVA_HOME");if(!value)value="/usr/lib/jvm/java-21-openjdk-amd64";}else if(!strcmp(key,"java.class.path"))value=".";else if(!strcmp(key,"java.io.tmpdir"))value="/tmp";else if(!strcmp(key,"os.name"))value="Linux";else if(!strcmp(key,"os.arch"))value="x86_64";else if(!strcmp(key,"os.version"))value="";else if(!strcmp(key,"sun.arch.data.model"))value="64";else if(!strcmp(key,"file.encoding"))value="UTF-8";else if(!strcmp(key,"native.encoding"))value="UTF-8";else if(!strcmp(key,"file.separator"))value="/";else if(!strcmp(key,"path.separator"))value=":";else if(!strcmp(key,"line.separator"))value="\n";else if(!strcmp(key,"user.dir"))value=".";else if(!strcmp(key,"user.home"))value=getenv("HOME");else if(!strcmp(key,"user.name"))value=getenv("USER");else if(!strcmp(key,"user.language"))value="en";else if(!strcmp(key,"user.country"))value="CA";return value;}
static int host_property(int environment){char key[256];size_t length;if(jvmr_heap_string_copy(current_frame.stack[current_frame.sp-1],key,sizeof(key),&length))return -1;return host_string_result(host_property_value(key,environment));}
static int host_property_default(void){char key[256];size_t length;uint64_t fallback=current_frame.stack[current_frame.sp-1];if(jvmr_heap_string_copy(current_frame.stack[current_frame.sp-2],key,sizeof(key),&length))return -1;const char *value=host_property_value(key,0);current_frame.sp--;if(value)return host_string_result(value);current_frame.stack[current_frame.sp-1]=fallback;return 0;}
static int file_path(uint64_t file,char *path,size_t capacity){uint64_t value;if(jvmr_heap_field_load_named(file,"path","Ljava/lang/String;",&value))return -1;size_t length;return jvmr_heap_string_copy(value,path,capacity,&length);}
static int file_attributes(uint64_t file){char path[4096];struct stat info;if(file_path(file,path,sizeof(path))||stat(path,&info))return 0;int result=1;if(S_ISREG(info.st_mode))result|=2;if(S_ISDIR(info.st_mode))result|=4;if(path[0]=='.')result|=8;return result;}
static int nio_path_copy(uint64_t reference,char *path,size_t capacity){const JVMR_Class *path_class=jvmr_runtime_load_class_name("sun/nio/fs/UnixPath");const JVMR_Field *field=path_class?jvmr_class_find_field(path_class,"path","[B"):NULL;int offset=field?jvmr_runtime_field_offset(path_class,path_class,field):-1;uint64_t bytes;if(offset<0||jvmr_heap_field_load(reference,(uint16_t)offset,&bytes))return -1;int32_t length;if(jvmr_heap_array_length(bytes,&length)||length<0||((size_t)length>=capacity))return -1;for(int32_t i=0;i<length;i++){uint64_t value;if(jvmr_heap_array_load(bytes,i,&value))return -1;path[i]=(char)(uint8_t)value;}path[length]=0;return 0;}
static int nio_path_result(uint64_t string_reference){char path[4096];size_t length;if(jvmr_heap_string_copy(string_reference,path,sizeof(path),&length))return -1;const JVMR_Class *path_class=jvmr_runtime_load_class_name("sun/nio/fs/UnixPath");const JVMR_Field *field=path_class?jvmr_class_find_field(path_class,"path","[B"):NULL;if(!path_class||!field)return -1;int object=jvmr_heap_new_object(path_class);int bytes=jvmr_heap_new_array(JVMR_HEAP_PRIMITIVE_ARRAY,(int32_t)length);int offset=jvmr_runtime_field_offset(path_class,path_class,field);if(object<0||bytes<0||offset<0)return -1;for(size_t i=0;i<length;i++)if(jvmr_heap_array_store((uint64_t)bytes,(int32_t)i,(uint8_t)path[i]))return -1;if(jvmr_heap_field_store((uint64_t)object,(uint16_t)offset,(uint64_t)bytes))return -1;current_frame.sp-=2;current_frame.stack[current_frame.sp++]=(uint64_t)object;return 0;}
static int nio_read_bytes(uint64_t path_reference){char path[4096];struct stat info;FILE *file;if(nio_path_copy(path_reference,path,sizeof(path))||stat(path,&info)||!S_ISREG(info.st_mode)){jvmr_throw_named("java/io/IOException");return 0;}int array=jvmr_heap_new_array(JVMR_HEAP_PRIMITIVE_ARRAY,(int32_t)info.st_size);if(array<0||(file=fopen(path,"rb"))==NULL){jvmr_throw_named("java/io/IOException");return 0;}for(int32_t i=0;i<info.st_size;i++){int value=fgetc(file);if(value==EOF||jvmr_heap_array_store((uint64_t)array,i,(uint8_t)value)){fclose(file);jvmr_throw_named("java/io/IOException");return 0;}}fclose(file);current_frame.stack[current_frame.sp-1]=(uint64_t)array;return 0;}
static int nio_read_string(uint64_t path_reference){char path[4096],text[65536];FILE *file;if(nio_path_copy(path_reference,path,sizeof(path))||(file=fopen(path,"rb"))==NULL){jvmr_throw_named("java/io/IOException");return 0;}size_t length=fread(text,1,sizeof(text)-1,file);int failed=ferror(file);fclose(file);if(failed){jvmr_throw_named("java/io/IOException");return 0;}text[length]=0;return host_string_result(text);}
static int nio_mkdirs(uint64_t path_reference){char path[4096];if(nio_path_copy(path_reference,path,sizeof(path)))return -1;for(char *p=path+1;*p;p++)if(*p=='/'){*p=0;if(mkdir(path,0755)&&errno!=EEXIST)return -1;*p='/';}if(mkdir(path,0755)&&errno!=EEXIST)return -1;return 0;}
static int nio_write_array(uint64_t path_reference,uint64_t array){char path[4096];int32_t length;FILE *file;if(nio_path_copy(path_reference,path,sizeof(path))||jvmr_heap_array_length(array,&length)||(file=fopen(path,"wb"))==NULL){jvmr_throw_named("java/io/IOException");return 0;}for(int32_t i=0;i<length;i++){uint64_t value;if(jvmr_heap_array_load(array,i,&value)||fputc((int)(value&0xff),file)==EOF){fclose(file);jvmr_throw_named("java/io/IOException");return 0;}}fclose(file);return 0;}
static int nio_write_string(uint64_t path_reference,uint64_t string_reference){char path[4096],text[65536];size_t length;FILE *file;if(nio_path_copy(path_reference,path,sizeof(path))||jvmr_heap_string_copy(string_reference,text,sizeof(text),&length)||(file=fopen(path,"wb"))==NULL){jvmr_throw_named("java/io/IOException");return 0;}size_t written=fwrite(text,1,length,file);int failed=ferror(file)||written!=length;fclose(file);if(failed)jvmr_throw_named("java/io/IOException");return 0;}
static FILE **input_stream_slot(uint64_t reference){if(reference==0)return NULL;if(reference>=input_stream_capacity){size_t capacity=input_stream_capacity?input_stream_capacity:64;while(capacity<=reference)capacity*=2;FILE **next=realloc(input_streams,capacity*sizeof(*next));if(!next)return NULL;memset(next+input_stream_capacity,0,(capacity-input_stream_capacity)*sizeof(*next));input_streams=next;input_stream_capacity=capacity;}return &input_streams[reference];}
static FILE **output_stream_slot(uint64_t reference){if(reference==0)return NULL;if(reference>=output_stream_capacity){size_t capacity=output_stream_capacity?output_stream_capacity:64;while(capacity<=reference)capacity*=2;FILE **next=realloc(output_streams,capacity*sizeof(*next));if(!next)return NULL;memset(next+output_stream_capacity,0,(capacity-output_stream_capacity)*sizeof(*next));output_streams=next;output_stream_capacity=capacity;}return &output_streams[reference];}
static int bootstrap_class_result(uint64_t name_reference){char name[512];size_t length;if(jvmr_heap_string_copy(name_reference,name,sizeof(name),&length))return -1;for(size_t i=0;i<length;i++)if(name[i]=='.')name[i]='/';const JVMR_Class *represented=jvmr_runtime_load_class_name(name);if(!represented){current_frame.stack[current_frame.sp-1]=0;return 0;}const JVMR_Class *class_class=jvmr_runtime_load_class_name("java/lang/Class");int mirror=jvmr_heap_new_class_mirror(represented,class_class);if(mirror<0)return -1;current_frame.stack[current_frame.sp-1]=(uint64_t)mirror;return 0;}
static int class_name_result(uint64_t reference){const JVMR_Class *represented;if(jvmr_heap_class_mirror(reference,&represented))return -1;int result=jvmr_heap_new_string((const uint8_t *)(represented->name?represented->name:""),(uint16_t)strlen(represented->name?represented->name:""),jvmr_runtime_class());if(result<0)return -1;current_frame.stack[current_frame.sp++]=(uint64_t)result;return 0;}
static int class_mirror_result(const JVMR_Class *represented){const JVMR_Class *class_class=jvmr_runtime_load_class_name("java/lang/Class");int result=jvmr_heap_new_class_mirror(represented,class_class);if(result<0)return -1;current_frame.stack[current_frame.sp++]=(uint64_t)result;return 0;}
static int push_host_string(const char *value){const JVMR_Class *string_class=jvmr_runtime_load_class_name("java/lang/String");int reference=jvmr_heap_new_string((const uint8_t *)value,(uint16_t)strlen(value),string_class?string_class:jvmr_runtime_class());if(reference<0)return -1;current_frame.stack[current_frame.sp++]=(uint64_t)reference;return 0;}
static int string_copy(uint64_t reference,char *buffer,size_t capacity,size_t *length){return jvmr_heap_string_copy(reference,buffer,capacity,length);}
static int string_range_result(uint64_t receiver,int32_t start,int32_t end){char source[4096];size_t length;if(string_copy(receiver,source,sizeof(source),&length)||start<0||end<start||(size_t)end>length)return -1;int reference=jvmr_heap_new_string((const uint8_t *)source+start,(uint16_t)(end-start),jvmr_heap_object_class(receiver));if(reference<0)return -1;current_frame.stack[current_frame.sp++]=(uint64_t)reference;return 0;}
static int descriptor_count(const char *descriptor){int count=0;for(const char *p=descriptor&&descriptor[0]=='('?descriptor+1:NULL;p&&*p&&*p!=')';p++){if(*p=='['){while(*p=='[')p++;if(*p=='L')while(*p&&*p!=';')p++;}else if(*p=='L'){while(*p&&*p!=';')p++;}count++;}return count;}
static int reflected_methods(uint64_t receiver,int public_only){const JVMR_Class *represented;if(jvmr_heap_class_mirror(receiver,&represented))return -1;const JVMR_Class *method_class=jvmr_runtime_load_class_name("java/lang/reflect/Method");int count=0;for(uint16_t i=0;i<represented->method_count;i++)if(!public_only||(represented->methods[i].access_flags&0x0001))count++;int array=jvmr_heap_new_array(JVMR_HEAP_REF_ARRAY,count);if(array<0)return -1;int position=0;for(uint16_t i=0;i<represented->method_count;i++){const JVMR_Method *method=&represented->methods[i];if(public_only&&!(method->access_flags&0x0001))continue;int mirror=jvmr_heap_new_method_mirror(method_class,represented,method);if(mirror<0||jvmr_heap_array_store((uint64_t)array,position++,(uint64_t)mirror))return -1;}current_frame.stack[current_frame.sp++]=(uint64_t)array;return 0;}
static int reflected_fields(uint64_t receiver,int public_only){const JVMR_Class *represented;if(jvmr_heap_class_mirror(receiver,&represented))return -1;const JVMR_Class *field_class=jvmr_runtime_load_class_name("java/lang/reflect/Field");int count=0;for(uint16_t i=0;i<represented->field_count;i++)if(!public_only||(represented->fields[i].access_flags&0x0001))count++;int array=jvmr_heap_new_array(JVMR_HEAP_REF_ARRAY,count);if(array<0)return -1;int position=0;for(uint16_t i=0;i<represented->field_count;i++)if(!public_only||(represented->fields[i].access_flags&0x0001)){int mirror=jvmr_heap_new_field_mirror(field_class,represented,&represented->fields[i]);if(mirror<0||jvmr_heap_array_store((uint64_t)array,position++,(uint64_t)mirror))return -1;}current_frame.stack[current_frame.sp++]=(uint64_t)array;return 0;}
static int reflected_field_lookup(uint64_t receiver,uint64_t name_reference,int public_only){const JVMR_Class *represented;if(jvmr_heap_class_mirror(receiver,&represented))return -1;char name[256];size_t length;if(jvmr_heap_string_copy(name_reference,name,sizeof(name),&length))return -1;const JVMR_Field *field=NULL;for(const JVMR_Class *current=represented;current&&!field;){for(uint16_t i=0;i<current->field_count;i++)if(current->fields[i].name&&!strcmp(current->fields[i].name,name)&&(!public_only||(current->fields[i].access_flags&0x0001))){field=&current->fields[i];represented=current;break;}if(!field&&!current->super_name)break;current=!field?jvmr_runtime_load_class_name(current->super_name):NULL;}if(!field)return -1;const JVMR_Class *field_class=jvmr_runtime_load_class_name("java/lang/reflect/Field");int mirror=jvmr_heap_new_field_mirror(field_class,represented,field);if(mirror<0)return -1;current_frame.stack[current_frame.sp++]=(uint64_t)mirror;return 0;}
static int reflected_method_lookup(uint64_t receiver,uint64_t name_reference,uint64_t parameter_array,int public_only){const JVMR_Class *represented;if(jvmr_heap_class_mirror(receiver,&represented))return -1;char name[256];size_t length;if(jvmr_heap_string_copy(name_reference,name,sizeof(name),&length))return -1;int32_t parameter_count=0;if(parameter_array&&jvmr_heap_array_length(parameter_array,&parameter_count))return -1;for(const JVMR_Class *current=represented;current;){for(uint16_t i=0;i<current->method_count;i++){const JVMR_Method *method=&current->methods[i];if(method->name&&!strcmp(method->name,name)&&(!public_only||(method->access_flags&0x0001))&&descriptor_count(method->descriptor)==parameter_count){const JVMR_Class *method_class=jvmr_runtime_load_class_name("java/lang/reflect/Method");int mirror=jvmr_heap_new_method_mirror(method_class,current,method);if(mirror<0)return -1;current_frame.stack[current_frame.sp++]=(uint64_t)mirror;return 0;}}if(!current->super_name)break;current=jvmr_runtime_load_class_name(current->super_name);}return -1;}
static int box_field_value(const char *descriptor,uint64_t value){const char *class_name=NULL;if(!descriptor||!descriptor[0])return -1;if(descriptor[0]=='I')class_name="java/lang/Integer";else if(descriptor[0]=='J')class_name="java/lang/Long";else if(descriptor[0]=='Z')class_name="java/lang/Boolean";else return -1;const JVMR_Class *klass=jvmr_runtime_load_class_name(class_name);if(!klass)return -1;const JVMR_Field *field=jvmr_class_find_field(klass,"value",descriptor);int reference=field?jvmr_heap_new_object(klass):-1;if(reference<0||jvmr_heap_field_store((uint64_t)reference,field->slot,value))return -1;current_frame.stack[current_frame.sp++]=(uint64_t)reference;return 0;}
static int reflected_field_value(uint64_t mirror,uint64_t object,int primitive){const JVMR_Class *declaring;const JVMR_Field *field;if(jvmr_heap_field_mirror(mirror,&declaring,&field))return -1;if(jvmr_ensure_initialized(declaring))return -1;uint64_t value;if(field->access_flags&0x0008)value=declaring->static_values[field->slot];else {const JVMR_Class *object_class=jvmr_heap_object_class(object);int offset=jvmr_runtime_field_offset(object_class,declaring,field);if(offset<0||jvmr_heap_field_load(object,(uint16_t)offset,&value))return -1;}if(primitive){if(field->descriptor&&field->descriptor[0]=='I'){current_frame.stack[current_frame.sp++]=(uint32_t)value;return 0;}return -1;}if(field->descriptor&&field->descriptor[0]=='L'){current_frame.stack[current_frame.sp++]=value;return 0;}return box_field_value(field->descriptor,value);}
static int unbox_argument(uint64_t reference,char type,uint64_t *value){if(type=='L'||type=='['){*value=reference;return 0;}const char *name=type=='I'?"java/lang/Integer":type=='J'?"java/lang/Long":type=='Z'?"java/lang/Boolean":NULL;const char *descriptor=type=='I'?"I":type=='J'?"J":type=='Z'?"Z":NULL;if(!name)return -1;const JVMR_Class *klass=jvmr_runtime_load_class_name(name);const JVMR_Field *field=klass?jvmr_class_find_field(klass,"value",descriptor):NULL;return field?jvmr_heap_field_load(reference,field->slot,value):-1;}
static int reflected_method_invoke(uint64_t mirror,uint64_t object,uint64_t argument_array){const JVMR_Class *declaring;const JVMR_Method *method;if(jvmr_heap_method_mirror(mirror,&declaring,&method))return -1;int expected=descriptor_count(method->descriptor),actual=0;if(argument_array&&jvmr_heap_array_length(argument_array,&actual))return -1;if(expected!=actual)return -1;uint64_t arguments[256];const char *p=method->descriptor+1;for(int i=0;i<expected;i++){char type=*p++;if(type=='['){while(*p=='[')p++;if(*p=='L')while(*p&&*p!=';')p++;type='L';}else if(type=='L')while(*p&&*p!=';')p++;if(*p==';')p++;uint64_t argument;if(jvmr_heap_array_load(argument_array,i,&argument))return -1;if(unbox_argument(argument,type,&arguments[i]))return -1;}return jvmr_invoke_reflected(declaring,method,object,arguments,(uint16_t)expected);}

int jvmr_native_invoke(const JVMR_Class *c,const JVMR_Method *m,int is_static){
	if(!c||!m)return 1;
	if((m->access_flags&0x0100)&&m->name&&!strcmp(m->name,"registerNatives")&&m->descriptor&&!strcmp(m->descriptor,"()V")){if(!is_static&&current_frame.sp)current_frame.sp--;return 0;}
	if((m->access_flags&0x0100)&&m->name&&!strcmp(m->name,"initIDs")&&m->descriptor&&!strcmp(m->descriptor,"()V")){return 0;}
	if(is_static&&c->name&&!strcmp(c->name,"jdk/internal/misc/VM")&&m->name&&!strcmp(m->name,"initialize")&&m->descriptor&&!strcmp(m->descriptor,"()V")){return 0;}
	if(is_static&&c->name&&!strcmp(c->name,"jdk/internal/misc/CDS")&&m->name&&!strcmp(m->name,"isDumpingClassList0")&&m->descriptor&&!strcmp(m->descriptor,"()Z")){current_frame.stack[current_frame.sp++]=0;return 0;}
	if(is_static&&c->name&&!strcmp(c->name,"jdk/internal/misc/CDS")&&m->name&&!strcmp(m->name,"isDumpingArchive0")&&m->descriptor&&!strcmp(m->descriptor,"()Z")){current_frame.stack[current_frame.sp++]=0;return 0;}
	if(is_static&&c->name&&!strcmp(c->name,"jdk/internal/misc/CDS")&&m->name&&!strcmp(m->name,"isSharingEnabled0")&&m->descriptor&&!strcmp(m->descriptor,"()Z")){current_frame.stack[current_frame.sp++]=0;return 0;}
	if(is_static&&c->name&&!strcmp(c->name,"jdk/internal/misc/CDS")&&m->name&&!strcmp(m->name,"initializeFromArchive")&&m->descriptor&&!strcmp(m->descriptor,"(Ljava/lang/Class;)V")){current_frame.sp--;return 0;}
	if(is_static&&c->name&&!strcmp(c->name,"jdk/internal/misc/CDS")&&m->name&&!strcmp(m->name,"getRandomSeedForDumping")&&m->descriptor&&!strcmp(m->descriptor,"()J")){current_frame.stack[current_frame.sp++]=0;return 0;}
	if(is_static&&c->name&&!strcmp(c->name,"jdk/internal/reflect/Reflection")&&m->name&&!strcmp(m->name,"getCallerClass")&&m->descriptor&&!strcmp(m->descriptor,"()Ljava/lang/Class;")){current_frame.stack[current_frame.sp++]=0;return 0;}
	if(!is_static&&c->name&&!strcmp(c->name,"java/lang/Throwable")&&m->name&&!strcmp(m->name,"fillInStackTrace")&&m->descriptor&&!strcmp(m->descriptor,"(I)Ljava/lang/Throwable;")){current_frame.sp--;return 0;}
	if(is_static&&matches(c,m,"java/lang/Class","getPrimitiveClass","(Ljava/lang/String;)Ljava/lang/Class;")){int reference=jvmr_heap_new_object(c);if(reference<0)return -1;current_frame.sp--;current_frame.stack[current_frame.sp++]=(uint64_t)reference;return 0;}
	if(is_static&&matches(c,m,"java/lang/Class","forName","(Ljava/lang/String;)Ljava/lang/Class;")){char name[256];size_t length;uint64_t key=current_frame.stack[current_frame.sp-1];if(jvmr_heap_string_copy(key,name,sizeof(name),&length))return -1;for(size_t i=0;i<length;i++)if(name[i]=='.')name[i]='/';const JVMR_Class *represented=jvmr_runtime_load_class_name(name);if(!represented)return -1;int reference=jvmr_heap_new_class_mirror(represented,c);if(reference<0)return -1;current_frame.stack[current_frame.sp-1]=(uint64_t)reference;return 0;}
	if(!is_static&&matches(c,m,"java/lang/Class","getName","()Ljava/lang/String;")){uint64_t receiver=current_frame.stack[--current_frame.sp];return class_name_result(receiver);}
	if(!is_static&&matches(c,m,"java/lang/Class","getSuperclass","()Ljava/lang/Class;")){uint64_t receiver=current_frame.stack[--current_frame.sp];const JVMR_Class *represented;if(jvmr_heap_class_mirror(receiver,&represented))return -1;if(!represented->super_name){current_frame.stack[current_frame.sp++]=0;return 0;}const JVMR_Class *super_class=jvmr_runtime_load_class_name(represented->super_name);return class_mirror_result(super_class);}
	if(!is_static&&matches(c,m,"java/lang/Class","isInterface","()Z")){uint64_t receiver=current_frame.stack[--current_frame.sp];const JVMR_Class *represented;int result=!jvmr_heap_class_mirror(receiver,&represented)&&(represented->access_flags&0x0200);current_frame.stack[current_frame.sp++]=(uint32_t)result;return 0;}
	if(!is_static&&matches(c,m,"java/lang/Class","getModifiers","()I")){uint64_t receiver=current_frame.stack[--current_frame.sp];const JVMR_Class *represented;if(jvmr_heap_class_mirror(receiver,&represented))return -1;current_frame.stack[current_frame.sp++]=represented->access_flags;return 0;}
	if(!is_static&&matches(c,m,"java/lang/Class","getDeclaredMethods0","(Z)[Ljava/lang/reflect/Method;")){int public_only=(int)current_frame.stack[--current_frame.sp];uint64_t receiver=current_frame.stack[--current_frame.sp];return reflected_methods(receiver,public_only);}
	if(!is_static&&matches(c,m,"java/lang/Class","getDeclaredFields0","(Z)[Ljava/lang/reflect/Field;")){int public_only=(int)current_frame.stack[--current_frame.sp];uint64_t receiver=current_frame.stack[--current_frame.sp];return reflected_fields(receiver,public_only);}
	if(!is_static&&matches(c,m,"java/lang/Class","getDeclaredMethods","()[Ljava/lang/reflect/Method;")){uint64_t receiver=current_frame.stack[--current_frame.sp];return reflected_methods(receiver,0);}
	if(!is_static&&matches(c,m,"java/lang/Class","getDeclaredFields","()[Ljava/lang/reflect/Field;")){uint64_t receiver=current_frame.stack[--current_frame.sp];return reflected_fields(receiver,0);}
	if(!is_static&&matches(c,m,"java/lang/Class","getDeclaredField","(Ljava/lang/String;)Ljava/lang/reflect/Field;")){uint64_t name=current_frame.stack[--current_frame.sp],receiver=current_frame.stack[--current_frame.sp];return reflected_field_lookup(receiver,name,0);}
	if(!is_static&&matches(c,m,"java/lang/Class","getField","(Ljava/lang/String;)Ljava/lang/reflect/Field;")){uint64_t name=current_frame.stack[--current_frame.sp],receiver=current_frame.stack[--current_frame.sp];return reflected_field_lookup(receiver,name,1);}
	if(!is_static&&matches(c,m,"java/lang/Class","getDeclaredMethod","(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;")){uint64_t parameters=current_frame.stack[--current_frame.sp],name=current_frame.stack[--current_frame.sp],receiver=current_frame.stack[--current_frame.sp];return reflected_method_lookup(receiver,name,parameters,0);}
	if(!is_static&&matches(c,m,"java/lang/Class","getMethod","(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;")){uint64_t parameters=current_frame.stack[--current_frame.sp],name=current_frame.stack[--current_frame.sp],receiver=current_frame.stack[--current_frame.sp];return reflected_method_lookup(receiver,name,parameters,1);}
	if(!is_static&&matches(c,m,"java/lang/Class","isAssignableFrom","(Ljava/lang/Class;)Z")){uint64_t other=current_frame.stack[--current_frame.sp],receiver=current_frame.stack[--current_frame.sp];const JVMR_Class *target,*candidate;int result=!jvmr_heap_class_mirror(receiver,&target)&&!jvmr_heap_class_mirror(other,&candidate)&&jvmr_runtime_class_is_assignable(candidate,target);current_frame.stack[current_frame.sp++]=(uint32_t)result;return 0;}
	if(!is_static&&matches(c,m,"java/lang/Class","isInstance","(Ljava/lang/Object;)Z")){uint64_t object=current_frame.stack[--current_frame.sp],receiver=current_frame.stack[--current_frame.sp];const JVMR_Class *target;int result=!jvmr_heap_class_mirror(receiver,&target)&&jvmr_runtime_is_instance(object,target);current_frame.stack[current_frame.sp++]=(uint32_t)result;return 0;}
	if(is_static&&matches(c,m,"java/lang/System","getProperty","(Ljava/lang/String;)Ljava/lang/String;"))return host_property(0);
	if(is_static&&matches(c,m,"java/lang/System","getProperty","(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;"))return host_property_default();
	if(is_static&&matches(c,m,"java/lang/System","getenv","(Ljava/lang/String;)Ljava/lang/String;"))return host_property(1);
	if(is_static&&matches(c,m,"java/lang/System","mapLibraryName","(Ljava/lang/String;)Ljava/lang/String;")){char name[256];size_t length;if(jvmr_heap_string_copy(current_frame.stack[current_frame.sp-1],name,sizeof(name),&length))return -1;char mapped[320];snprintf(mapped,sizeof(mapped),"lib%s.so",name);return host_string_result(mapped);}
	if(is_static&&matches(c,m,"java/nio/file/Path","of","(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path;"))return nio_path_result(current_frame.stack[current_frame.sp-2]);
	if(is_static&&matches(c,m,"java/nio/file/Files","exists","(Ljava/nio/file/Path;[Ljava/nio/file/LinkOption;)Z")){char path[4096];int result=!nio_path_copy(current_frame.stack[current_frame.sp-2],path,sizeof(path))&&!access(path,F_OK);current_frame.sp-=2;current_frame.stack[current_frame.sp++]=(uint32_t)result;return 0;}
	if(is_static&&matches(c,m,"java/nio/file/Files","size","(Ljava/nio/file/Path;)J")){char path[4096];struct stat info;int ok=!nio_path_copy(current_frame.stack[current_frame.sp-1],path,sizeof(path))&&!stat(path,&info);if(!ok){jvmr_throw_named("java/io/IOException");return 0;}current_frame.stack[current_frame.sp-1]=(uint64_t)info.st_size;return 0;}
	if(is_static&&matches(c,m,"java/nio/file/Files","readAllBytes","(Ljava/nio/file/Path;)[B"))return nio_read_bytes(current_frame.stack[current_frame.sp-1]);
	if(is_static&&matches(c,m,"java/nio/file/Files","isRegularFile","(Ljava/nio/file/Path;[Ljava/nio/file/LinkOption;)Z")){char path[4096];struct stat info;int result=!nio_path_copy(current_frame.stack[current_frame.sp-2],path,sizeof(path))&&!stat(path,&info)&&S_ISREG(info.st_mode);current_frame.sp-=2;current_frame.stack[current_frame.sp++]=(uint32_t)result;return 0;}
	if(is_static&&matches(c,m,"java/nio/file/Files","isDirectory","(Ljava/nio/file/Path;[Ljava/nio/file/LinkOption;)Z")){char path[4096];struct stat info;int result=!nio_path_copy(current_frame.stack[current_frame.sp-2],path,sizeof(path))&&!stat(path,&info)&&S_ISDIR(info.st_mode);current_frame.sp-=2;current_frame.stack[current_frame.sp++]=(uint32_t)result;return 0;}
	if(is_static&&matches(c,m,"java/nio/file/Files","readString","(Ljava/nio/file/Path;)Ljava/lang/String;"))return nio_read_string(current_frame.stack[current_frame.sp-1]);
	if(is_static&&matches(c,m,"java/nio/file/Files","createDirectories","(Ljava/nio/file/Path;[Ljava/nio/file/attribute/FileAttribute;)Ljava/nio/file/Path;")){uint64_t path=current_frame.stack[current_frame.sp-2];if(nio_mkdirs(path)){jvmr_throw_named("java/io/IOException");return 0;}current_frame.sp-=2;current_frame.stack[current_frame.sp++]=path;return 0;}
	if(is_static&&matches(c,m,"java/nio/file/Files","write","(Ljava/nio/file/Path;[B[Ljava/nio/file/OpenOption;)Ljava/nio/file/Path;")){uint64_t path=current_frame.stack[current_frame.sp-3],array=current_frame.stack[current_frame.sp-2];if(nio_write_array(path,array))return 0;current_frame.sp-=3;current_frame.stack[current_frame.sp++]=path;return 0;}
	if(is_static&&matches(c,m,"java/nio/file/Files","writeString","(Ljava/nio/file/Path;Ljava/lang/CharSequence;[Ljava/nio/file/OpenOption;)Ljava/nio/file/Path;")){uint64_t path=current_frame.stack[current_frame.sp-3],string=current_frame.stack[current_frame.sp-2];if(nio_write_string(path,string))return 0;current_frame.sp-=3;current_frame.stack[current_frame.sp++]=path;return 0;}
	if(!is_static&&matches(c,m,"java/io/UnixFileSystem","getBooleanAttributes0","(Ljava/io/File;)I")){uint64_t file=current_frame.stack[--current_frame.sp];current_frame.sp--;current_frame.stack[current_frame.sp++]=(uint32_t)file_attributes(file);return 0;}
	if(!is_static&&matches(c,m,"java/io/UnixFileSystem","checkAccess0","(Ljava/io/File;I)Z")){int mode=(int)current_frame.stack[--current_frame.sp],file=(int)current_frame.stack[--current_frame.sp];char path[4096];int result=!file_path((uint64_t)file,path,sizeof(path))&&!access(path,mode==0?R_OK:mode==1?W_OK:X_OK);current_frame.sp--;current_frame.stack[current_frame.sp++]=(uint32_t)result;return 0;}
	if(!is_static&&matches(c,m,"java/io/UnixFileSystem","getLastModifiedTime0","(Ljava/io/File;)J")){uint64_t file=current_frame.stack[--current_frame.sp];current_frame.sp--;char path[4096];struct stat info;uint64_t result=(!file_path(file,path,sizeof(path))&&!stat(path,&info))?(uint64_t)info.st_mtime*1000u:0;current_frame.stack[current_frame.sp++]=result;return 0;}
	if(!is_static&&matches(c,m,"java/io/UnixFileSystem","getLength0","(Ljava/io/File;)J")){uint64_t file=current_frame.stack[--current_frame.sp];current_frame.sp--;char path[4096];struct stat info;uint64_t result=(!file_path(file,path,sizeof(path))&&!stat(path,&info)&&S_ISREG(info.st_mode))?(uint64_t)info.st_size:0;current_frame.stack[current_frame.sp++]=result;return 0;}
	if(!is_static&&matches(c,m,"java/io/UnixFileSystem","canonicalize0","(Ljava/lang/String;)Ljava/lang/String;")){uint64_t value=current_frame.stack[--current_frame.sp];current_frame.stack[current_frame.sp-1]=value;return 0;}
	if(!is_static&&(!strcmp(c->name,"java/io/UnixFileSystem")||!strcmp(c->name,"java/io/FileSystem"))&&m->name&&!strcmp(m->name,"normalize")&&m->descriptor&&!strcmp(m->descriptor,"(Ljava/lang/String;)Ljava/lang/String;")){uint64_t value=current_frame.stack[--current_frame.sp];current_frame.stack[current_frame.sp-1]=value;return 0;}
	if(!is_static&&(!strcmp(c->name,"java/io/UnixFileSystem")||!strcmp(c->name,"java/io/FileSystem"))&&m->name&&!strcmp(m->name,"prefixLength")&&m->descriptor&&!strcmp(m->descriptor,"(Ljava/lang/String;)I")){uint64_t value=current_frame.stack[--current_frame.sp];char path[4096];size_t length;int result=!jvmr_heap_string_copy(value,path,sizeof(path),&length)&&path[0]=='/'?1:0;current_frame.sp--;current_frame.stack[current_frame.sp++]=(uint32_t)result;return 0;}
	if(!is_static&&(!strcmp(c->name,"java/io/UnixFileSystem")||!strcmp(c->name,"java/io/FileSystem"))&&m->name&&!strcmp(m->name,"getSeparator")&&m->descriptor&&!strcmp(m->descriptor,"()C")){current_frame.sp--;current_frame.stack[current_frame.sp++]=(uint32_t)'/';return 0;}
	if(!is_static&&(!strcmp(c->name,"java/io/UnixFileSystem")||!strcmp(c->name,"java/io/FileSystem"))&&m->name&&!strcmp(m->name,"getPathSeparator")&&m->descriptor&&!strcmp(m->descriptor,"()C")){current_frame.sp--;current_frame.stack[current_frame.sp++]=(uint32_t)':';return 0;}
	if(!is_static&&(!strcmp(c->name,"java/io/UnixFileSystem")||!strcmp(c->name,"java/io/FileSystem"))&&m->name&&!strcmp(m->name,"getDefaultParent")&&m->descriptor&&!strcmp(m->descriptor,"()Ljava/lang/String;")){current_frame.sp--;return push_host_string("/");}
	if(!is_static&&(!strcmp(c->name,"java/io/UnixFileSystem")||!strcmp(c->name,"java/io/FileSystem"))&&m->name&&!strcmp(m->name,"isInvalid")&&m->descriptor&&!strcmp(m->descriptor,"(Ljava/io/File;)Z")){current_frame.sp-=2;current_frame.stack[current_frame.sp++]=0;return 0;}
	if(!is_static&&!strcmp(c->name,"java/io/FileSystem")&&m->name&&!strcmp(m->name,"getBooleanAttributes")&&m->descriptor&&!strcmp(m->descriptor,"(Ljava/io/File;)I")){uint64_t file=current_frame.stack[--current_frame.sp];current_frame.sp--;current_frame.stack[current_frame.sp++]=(uint32_t)file_attributes(file);return 0;}
	if(!is_static&&!strcmp(c->name,"java/io/FileSystem")&&m->name&&!strcmp(m->name,"getLength")&&m->descriptor&&!strcmp(m->descriptor,"(Ljava/io/File;)J")){uint64_t file=current_frame.stack[--current_frame.sp];current_frame.sp--;char path[4096];struct stat info;uint64_t result=(!file_path(file,path,sizeof(path))&&!stat(path,&info)&&S_ISREG(info.st_mode))?(uint64_t)info.st_size:0;current_frame.stack[current_frame.sp++]=result;return 0;}
	if(!is_static&&matches(c,m,"java/io/FileInputStream","open0","(Ljava/lang/String;)V")){uint64_t path_reference=current_frame.stack[--current_frame.sp],stream=current_frame.stack[--current_frame.sp];char path[4096];size_t length;FILE **slot;if(jvmr_heap_string_copy(path_reference,path,sizeof(path),&length)||(slot=input_stream_slot(stream))==NULL){jvmr_throw_named("java/io/FileNotFoundException");return 0;}if(*slot)fclose(*slot);*slot=fopen(path,"rb");if(!*slot){jvmr_throw_named("java/io/FileNotFoundException");return 0;}return 0;}
	if(!is_static&&matches(c,m,"java/io/FileInputStream","read0","()I")){uint64_t stream=current_frame.stack[--current_frame.sp];FILE **slot=input_stream_slot(stream);int value=(slot&&*slot)?fgetc(*slot):-1;current_frame.stack[current_frame.sp++]=(uint32_t)value;return 0;}
	if(!is_static&&matches(c,m,"java/io/FileInputStream","readBytes","([BII)I")){int32_t length=(int32_t)current_frame.stack[--current_frame.sp],offset=(int32_t)current_frame.stack[--current_frame.sp];uint64_t array=current_frame.stack[--current_frame.sp],stream=current_frame.stack[--current_frame.sp];FILE **slot=input_stream_slot(stream);int32_t count=0;if(slot&&*slot&&length>0){for(;count<length;count++){int value=fgetc(*slot);if(value==EOF)break;if(jvmr_heap_array_store(array,offset+count,(uint32_t)(uint8_t)value))break;}}current_frame.stack[current_frame.sp++]=(uint32_t)count;return 0;}
	if(!is_static&&matches(c,m,"java/io/FileInputStream","available0","()I")){uint64_t stream=current_frame.stack[--current_frame.sp];FILE **slot=input_stream_slot(stream);long current=0,end=0;if(slot&&*slot){current=ftell(*slot);fseek(*slot,0,SEEK_END);end=ftell(*slot);fseek(*slot,current,SEEK_SET);}current_frame.stack[current_frame.sp++]=(uint32_t)(end>current?end-current:0);return 0;}
	if(!is_static&&matches(c,m,"java/io/FileInputStream","skip0","(J)J")){int64_t amount=(int64_t)current_frame.stack[--current_frame.sp];uint64_t stream=current_frame.stack[--current_frame.sp];FILE **slot=input_stream_slot(stream);long before=slot&&*slot?ftell(*slot):-1;long target=before>=0?before+(long)amount:-1;int64_t skipped=0;if(slot&&*slot&&before>=0&&!fseek(*slot,target,SEEK_SET))skipped=(int64_t)(target-before);current_frame.stack[current_frame.sp++]=(uint64_t)skipped;return 0;}
	if(!is_static&&matches(c,m,"java/io/FileInputStream","close0","()V")){uint64_t stream=current_frame.stack[--current_frame.sp];FILE **slot=input_stream_slot(stream);if(slot&&*slot){fclose(*slot);*slot=NULL;}return 0;}
	if(!is_static&&matches(c,m,"java/io/FileDescriptor","close0","()V")){current_frame.sp--;return 0;}
	if(!is_static&&matches(c,m,"java/io/FileDescriptor","sync0","()V")){current_frame.sp--;return 0;}
	if(!is_static&&matches(c,m,"java/io/FileOutputStream","open0","(Ljava/lang/String;Z)V")){int append=(int)current_frame.stack[--current_frame.sp],path_reference=(int)current_frame.stack[--current_frame.sp],stream=(int)current_frame.stack[--current_frame.sp];char path[4096];size_t length;FILE **slot;if(jvmr_heap_string_copy((uint64_t)path_reference,path,sizeof(path),&length)||(slot=output_stream_slot((uint64_t)stream))==NULL){jvmr_throw_named("java/io/FileNotFoundException");return 0;}if(*slot)fclose(*slot);*slot=fopen(path,append?"ab":"wb");if(!*slot){jvmr_throw_named("java/io/FileNotFoundException");return 0;}return 0;}
	if(!is_static&&matches(c,m,"java/io/FileOutputStream","write","(IZ)V")){current_frame.sp--;int value=(int)current_frame.stack[--current_frame.sp];uint64_t stream=current_frame.stack[--current_frame.sp];FILE **slot=output_stream_slot(stream);if(!slot||!*slot||fputc(value&0xff,*slot)==EOF)jvmr_throw_named("java/io/IOException");else fflush(*slot);return 0;}
	if(!is_static&&matches(c,m,"java/io/FileOutputStream","writeBytes","([BIIZ)V")){current_frame.sp--;int32_t length=(int32_t)current_frame.stack[--current_frame.sp],offset=(int32_t)current_frame.stack[--current_frame.sp];uint64_t array=current_frame.stack[--current_frame.sp],stream=current_frame.stack[--current_frame.sp];FILE **slot=output_stream_slot(stream);int failed=!(slot&&*slot&&length>=0);for(int32_t i=0;!failed&&i<length;i++){uint64_t value;if(jvmr_heap_array_load(array,offset+i,&value)||fputc((int)(value&0xff),*slot)==EOF)failed=1;}if(!failed)fflush(*slot);else jvmr_throw_named("java/io/IOException");return 0;}
	if(is_static&&matches(c,m,"java/lang/System","identityHashCode","(Ljava/lang/Object;)I")){uint64_t reference=current_frame.stack[current_frame.sp-1];current_frame.stack[current_frame.sp-1]=(uint32_t)reference;return 0;}
	if(is_static&&matches(c,m,"java/lang/ClassLoader","findBootstrapClass","(Ljava/lang/String;)Ljava/lang/Class;"))return bootstrap_class_result(current_frame.stack[current_frame.sp-1]);
	if(!is_static&&matches(c,m,"java/lang/ClassLoader","findLoadedClass0","(Ljava/lang/String;)Ljava/lang/Class;")){uint64_t name=current_frame.stack[--current_frame.sp];current_frame.stack[current_frame.sp-1]=name;return bootstrap_class_result(name);}
	if(is_static&&matches(c,m,"java/lang/ClassLoader","getBuiltinAppClassLoader","()Ljava/lang/ClassLoader;")){if(!system_classloader_reference){system_classloader_reference=(uint64_t)jvmr_heap_new_object(c);if(!system_classloader_reference)return -1;}current_frame.stack[current_frame.sp++]=system_classloader_reference;return 0;}
	if(is_static&&matches(c,m,"java/lang/Runtime","getRuntime","()Ljava/lang/Runtime;")){int reference=jvmr_heap_new_object(c);if(reference<0)return -1;current_frame.stack[current_frame.sp++]=(uint64_t)reference;return 0;}
	if(!is_static&&matches(c,m,"java/lang/Runtime","availableProcessors","()I")){current_frame.stack[current_frame.sp-1]=1;return 0;}
	if(is_static&&matches(c,m,"java/lang/Class","desiredAssertionStatus0","(Ljava/lang/Class;)Z")){current_frame.stack[current_frame.sp-1]=0;return 0;}
	if(!is_static&&matches(c,m,"java/lang/Object","notify","()V")){current_frame.sp--;return 0;}
	if(!is_static&&matches(c,m,"java/lang/Object","notifyAll","()V")){current_frame.sp--;return 0;}
	if(!is_static&&matches(c,m,"java/lang/Object","wait0","(J)V")){current_frame.sp-=2;return 0;}
	if(is_static&&matches(c,m,"java/lang/Thread","currentThread","()Ljava/lang/Thread;")){if(!main_thread_reference){main_thread_reference=(uint64_t)jvmr_heap_new_object(c);if(!main_thread_reference)return -1;}current_frame.stack[current_frame.sp++]=main_thread_reference;return 0;}
	if(is_static&&matches(c,m,"java/lang/Thread","activeCount","()I")){current_frame.stack[current_frame.sp++]=1;return 0;}
	if(is_static&&matches(c,m,"java/lang/Thread","yield","()V"))return 0;
	if(is_static&&matches(c,m,"java/lang/Thread","sleep","(J)V")){current_frame.sp--;return 0;}
	if(!is_static&&matches(c,m,"java/lang/Thread","getName","()Ljava/lang/String;")){current_frame.sp--;return push_host_string("main");}
	if(!is_static&&matches(c,m,"java/lang/Thread","isDaemon","()Z")){current_frame.sp--;current_frame.stack[current_frame.sp++]=0;return 0;}
	if(!is_static&&matches(c,m,"java/lang/Thread","isAlive","()Z")){current_frame.sp--;current_frame.stack[current_frame.sp++]=1;return 0;}
	if(!is_static&&matches(c,m,"java/lang/Thread","getPriority","()I")){current_frame.sp--;current_frame.stack[current_frame.sp++]=5;return 0;}
	if(!is_static&&matches(c,m,"java/lang/Thread","getId","()J")){current_frame.sp--;current_frame.stack[current_frame.sp++]=1;return 0;}
	if(!is_static&&matches(c,m,"java/lang/Thread","start","()V")){current_frame.sp--;return 0;}
	if(is_static&&matches(c,m,"java/lang/Integer","valueOf","(I)Ljava/lang/Integer;"))return boxed_value(c,"I",(uint32_t)int_arg(1));
	if(!is_static&&matches(c,m,"java/lang/Integer","intValue","()I")){uint64_t receiver=current_frame.stack[--current_frame.sp];const JVMR_Field *field=field_named(c,"value","I");uint64_t value;if(!field||jvmr_heap_field_load(receiver,field->slot,&value))return -1;current_frame.stack[current_frame.sp++]=(uint32_t)value;return 0;}
	if(is_static&&matches(c,m,"java/lang/Long","valueOf","(J)Ljava/lang/Long;"))return boxed_value(c,"J",current_frame.stack[current_frame.sp-1]);
	if(!is_static&&matches(c,m,"java/lang/Long","longValue","()J")){uint64_t receiver=current_frame.stack[--current_frame.sp];const JVMR_Field *field=field_named(c,"value","J");uint64_t value;if(!field||jvmr_heap_field_load(receiver,field->slot,&value))return -1;current_frame.stack[current_frame.sp++]=value;return 0;}
	if(is_static&&matches(c,m,"java/lang/Boolean","valueOf","(Z)Ljava/lang/Boolean;"))return boxed_value(c,"Z",(uint32_t)int_arg(1));
	if(!is_static&&matches(c,m,"java/lang/Boolean","booleanValue","()Z")){uint64_t receiver=current_frame.stack[--current_frame.sp];const JVMR_Field *field=field_named(c,"value","Z");uint64_t value;if(!field||jvmr_heap_field_load(receiver,field->slot,&value))return -1;current_frame.stack[current_frame.sp++]=(uint32_t)value;return 0;}
	if(is_static&&matches(c,m,"java/lang/System","currentTimeMillis","()J")){struct timespec t;clock_gettime(CLOCK_REALTIME,&t);current_frame.stack[current_frame.sp++]=(uint64_t)t.tv_sec*1000u+t.tv_nsec/1000000;return 0;}
	if(is_static&&matches(c,m,"java/lang/System","nanoTime","()J")){struct timespec t;clock_gettime(CLOCK_MONOTONIC,&t);current_frame.stack[current_frame.sp++]=(uint64_t)t.tv_sec*1000000000u+t.tv_nsec;return 0;}
	if(is_static&&matches(c,m,"java/lang/System","arraycopy","(Ljava/lang/Object;ILjava/lang/Object;II)V")){int32_t count=int_arg(1),dst_index=int_arg(2),src_index=int_arg(4);uint64_t dst=current_frame.stack[current_frame.sp-3],src=current_frame.stack[current_frame.sp-5];if(count<0){current_frame.pc=UINT32_MAX;return -1;}for(int32_t i=0;i<count;i++){uint64_t value;if(jvmr_heap_array_load(src,src_index+i,&value)||jvmr_heap_array_store(dst,dst_index+i,value)){current_frame.pc=UINT32_MAX;return -1;}}current_frame.sp-=5;return 0;}
	if(is_static&&matches(c,m,"java/lang/Math","abs","(I)I")){int32_t value=int_arg(1);current_frame.stack[current_frame.sp-1]=(uint32_t)(value<0?-value:value);return 0;}
	if(is_static&&matches(c,m,"java/lang/Math","max","(II)I")){int32_t b=int_arg(1),a=int_arg(2);current_frame.sp-=2;current_frame.stack[current_frame.sp++]=(uint32_t)(a>b?a:b);return 0;}
	if(is_static&&matches(c,m,"java/lang/Math","min","(II)I")){int32_t b=int_arg(1),a=int_arg(2);current_frame.sp-=2;current_frame.stack[current_frame.sp++]=(uint32_t)(a<b?a:b);return 0;}
	if(is_static&&matches(c,m,"java/lang/Math","sqrt","(D)D")){current_frame.stack[current_frame.sp-1]=double_value(sqrt(as_double(current_frame.stack[current_frame.sp-1])));return 0;}
	if(is_static&&matches(c,m,"java/lang/Float","floatToRawIntBits","(F)I")){current_frame.stack[current_frame.sp-1]=float_value(as_float(current_frame.stack[current_frame.sp-1]));return 0;}
	if(is_static&&matches(c,m,"java/lang/Float","floatToIntBits","(F)I")){current_frame.stack[current_frame.sp-1]=float_value(as_float(current_frame.stack[current_frame.sp-1]));return 0;}
	if(is_static&&matches(c,m,"java/lang/Float","intBitsToFloat","(I)F")){current_frame.stack[current_frame.sp-1]=float_value(as_float(current_frame.stack[current_frame.sp-1]));return 0;}
	if(is_static&&matches(c,m,"java/lang/Double","doubleToRawLongBits","(D)J")){current_frame.stack[current_frame.sp-1]=double_value(as_double(current_frame.stack[current_frame.sp-1]));return 0;}
	if(is_static&&matches(c,m,"java/lang/Double","doubleToLongBits","(D)J")){current_frame.stack[current_frame.sp-1]=double_value(as_double(current_frame.stack[current_frame.sp-1]));return 0;}
	if(is_static&&matches(c,m,"java/lang/Double","longBitsToDouble","(J)D")){current_frame.stack[current_frame.sp-1]=double_value(as_double(current_frame.stack[current_frame.sp-1]));return 0;}
	if(is_static&&matches(c,m,"java/lang/Math","floor","(D)D")){current_frame.stack[current_frame.sp-1]=double_value(floor(as_double(current_frame.stack[current_frame.sp-1])));return 0;}
	if(is_static&&matches(c,m,"java/lang/Math","ceil","(D)D")){current_frame.stack[current_frame.sp-1]=double_value(ceil(as_double(current_frame.stack[current_frame.sp-1])));return 0;}
	if(is_static&&matches(c,m,"java/lang/Math","sin","(D)D")){current_frame.stack[current_frame.sp-1]=double_value(sin(as_double(current_frame.stack[current_frame.sp-1])));return 0;}
	if(is_static&&matches(c,m,"java/lang/Math","cos","(D)D")){current_frame.stack[current_frame.sp-1]=double_value(cos(as_double(current_frame.stack[current_frame.sp-1])));return 0;}
	if(is_static&&matches(c,m,"java/lang/Math","pow","(DD)D")){double b=as_double(current_frame.stack[--current_frame.sp]),a=as_double(current_frame.stack[--current_frame.sp]);current_frame.stack[current_frame.sp++]=double_value(pow(a,b));return 0;}
	if(is_static&&matches(c,m,"java/lang/String","valueOf","(I)Ljava/lang/String;")){char text[32];int length=snprintf(text,sizeof(text),"%d",(int32_t)current_frame.stack[current_frame.sp-1]);int reference=jvmr_heap_new_string((const uint8_t *)text,(uint16_t)length,c);if(reference<0)return -1;current_frame.stack[current_frame.sp-1]=(uint64_t)reference;return 0;}
	if(!is_static&&matches(c,m,"java/lang/String","length","()I")){uint64_t receiver=current_frame.stack[--current_frame.sp];int32_t length;if(jvmr_heap_string_length(receiver,&length))return -1;current_frame.stack[current_frame.sp++]=(uint32_t)length;return 0;}
	if(!is_static&&matches(c,m,"java/lang/String","isEmpty","()Z")){uint64_t receiver=current_frame.stack[--current_frame.sp];int32_t length;if(jvmr_heap_string_length(receiver,&length))return -1;current_frame.stack[current_frame.sp++]=(uint32_t)(length==0);return 0;}
	if(!is_static&&matches(c,m,"java/lang/String","charAt","(I)C")){int32_t index=int_arg(1);uint64_t receiver=current_frame.stack[current_frame.sp-2];uint16_t value;if(jvmr_heap_string_char_at(receiver,index,&value))return -1;current_frame.sp-=2;current_frame.stack[current_frame.sp++]=value;return 0;}
	if(!is_static&&matches(c,m,"java/lang/String","substring","(I)Ljava/lang/String;")){int32_t start=int_arg(1);uint64_t receiver=current_frame.stack[current_frame.sp-2];current_frame.sp-=2;int32_t length;if(jvmr_heap_string_length(receiver,&length))return -1;return string_range_result(receiver,start,length);}
	if(!is_static&&matches(c,m,"java/lang/String","substring","(II)Ljava/lang/String;")){int32_t end=(int32_t)current_frame.stack[current_frame.sp-1],start=(int32_t)current_frame.stack[current_frame.sp-2];uint64_t receiver=current_frame.stack[current_frame.sp-3];current_frame.sp-=3;return string_range_result(receiver,start,end);}
	if(!is_static&&matches(c,m,"java/lang/String","indexOf","(Ljava/lang/String;)I")){uint64_t needle=current_frame.stack[--current_frame.sp],receiver=current_frame.stack[--current_frame.sp];char source[4096],target[4096];size_t source_length,target_length;int result=-1;if(!string_copy(receiver,source,sizeof(source),&source_length)&&!string_copy(needle,target,sizeof(target),&target_length)){char *found=strstr(source,target);result=found?(int)(found-source):-1;}current_frame.stack[current_frame.sp++]=(uint32_t)result;return 0;}
	if(!is_static&&matches(c,m,"java/lang/String","startsWith","(Ljava/lang/String;)Z")){uint64_t prefix=current_frame.stack[--current_frame.sp],receiver=current_frame.stack[--current_frame.sp];char source[4096],target[4096];size_t source_length,target_length;int result=!string_copy(receiver,source,sizeof(source),&source_length)&&!string_copy(prefix,target,sizeof(target),&target_length)&&target_length<=source_length&&!memcmp(source,target,target_length);current_frame.stack[current_frame.sp++]=(uint32_t)result;return 0;}
	if(!is_static&&matches(c,m,"java/lang/String","endsWith","(Ljava/lang/String;)Z")){uint64_t suffix=current_frame.stack[--current_frame.sp],receiver=current_frame.stack[--current_frame.sp];char source[4096],target[4096];size_t source_length,target_length;int result=!string_copy(receiver,source,sizeof(source),&source_length)&&!string_copy(suffix,target,sizeof(target),&target_length)&&target_length<=source_length&&!memcmp(source+source_length-target_length,target,target_length);current_frame.stack[current_frame.sp++]=(uint32_t)result;return 0;}
	if(!is_static&&matches(c,m,"java/lang/String","contains","(Ljava/lang/CharSequence;)Z")){uint64_t needle=current_frame.stack[--current_frame.sp],receiver=current_frame.stack[--current_frame.sp];char source[4096],target[4096];size_t source_length,target_length;int result=!string_copy(receiver,source,sizeof(source),&source_length)&&!string_copy(needle,target,sizeof(target),&target_length)&&strstr(source,target)!=NULL;current_frame.stack[current_frame.sp++]=(uint32_t)result;return 0;}
	if(!is_static&&matches(c,m,"java/lang/String","toLowerCase","()Ljava/lang/String;")){uint64_t receiver=current_frame.stack[--current_frame.sp];char text[4096];size_t length;if(string_copy(receiver,text,sizeof(text),&length))return -1;for(size_t i=0;i<length;i++)if(text[i]>='A'&&text[i]<='Z')text[i]=(char)(text[i]-'A'+'a');return push_host_string(text);}
	if(!is_static&&matches(c,m,"java/lang/String","equals","(Ljava/lang/Object;)Z")){uint64_t right=current_frame.stack[--current_frame.sp],left=current_frame.stack[--current_frame.sp];int equal=0;if(right)jvmr_heap_string_equals(left,right,&equal);current_frame.stack[current_frame.sp++]=(uint32_t)equal;return 0;}
	if(!is_static&&matches(c,m,"java/lang/String","hashCode","()I")){uint64_t receiver=current_frame.stack[--current_frame.sp];current_frame.stack[current_frame.sp++]=(uint32_t)jvmr_heap_string_hash(receiver);return 0;}
	if(!is_static&&matches(c,m,"java/lang/StringBuilder","<init>","()V")){current_frame.sp--;return 0;}
	if(!is_static&&matches(c,m,"java/lang/StringBuilder","<init>","(I)V")){current_frame.sp-=2;return 0;}
	if(!is_static&&matches(c,m,"java/lang/StringBuilder","<init>","(Ljava/lang/String;)V")){uint64_t value=current_frame.stack[--current_frame.sp],builder=current_frame.stack[--current_frame.sp];if(jvmr_heap_builder_append_string(builder,value))return -1;return 0;}
	if(!is_static&&matches(c,m,"java/lang/StringBuilder","append","(Ljava/lang/String;)Ljava/lang/StringBuilder;")){uint64_t value=current_frame.stack[--current_frame.sp],builder=current_frame.stack[--current_frame.sp];if(jvmr_heap_builder_append_string(builder,value))return -1;current_frame.stack[current_frame.sp++]=builder;return 0;}
	if(!is_static&&matches(c,m,"java/lang/StringBuilder","append","(I)Ljava/lang/StringBuilder;")){int32_t value=(int32_t)current_frame.stack[--current_frame.sp];uint64_t builder=current_frame.stack[--current_frame.sp];if(jvmr_heap_builder_append_int(builder,value))return -1;current_frame.stack[current_frame.sp++]=builder;return 0;}
	if(!is_static&&(!strcmp(c->name,"java/lang/StringBuilder")||!strcmp(c->name,"java/lang/AbstractStringBuilder"))&&m->name&&!strcmp(m->name,"append")&&m->descriptor&&!strncmp(m->descriptor,"(Ljava/lang/CharSequence;II)",28)){int32_t end=(int32_t)current_frame.stack[--current_frame.sp],start=(int32_t)current_frame.stack[--current_frame.sp];uint64_t value=current_frame.stack[--current_frame.sp],builder=current_frame.stack[--current_frame.sp];char text[4096];size_t length;if(string_copy(value,text,sizeof(text),&length)||start<0||end<start||(size_t)end>length||jvmr_heap_builder_append_chars(builder,text+start,(size_t)(end-start)))return -1;current_frame.stack[current_frame.sp++]=builder;return 0;}
	if(!is_static&&(!strcmp(c->name,"java/lang/StringBuilder")||!strcmp(c->name,"java/lang/AbstractStringBuilder"))&&m->name&&!strcmp(m->name,"append")&&m->descriptor&&!strcmp(m->descriptor,"(C)Ljava/lang/AbstractStringBuilder;")){uint16_t value=(uint16_t)current_frame.stack[--current_frame.sp];uint64_t builder=current_frame.stack[--current_frame.sp];char text[2]={(char)value,0};if(jvmr_heap_builder_append_chars(builder,text,1))return -1;current_frame.stack[current_frame.sp++]=builder;return 0;}
	if(!is_static&&matches(c,m,"java/lang/StringBuilder","toString","()Ljava/lang/String;")){uint64_t builder=current_frame.stack[--current_frame.sp];int string;if(jvmr_heap_builder_to_string(builder,&string))return -1;current_frame.stack[current_frame.sp++]=(uint64_t)string;return 0;}
	if(!is_static&&matches(c,m,"java/lang/Object","hashCode","()I")){uint64_t receiver=current_frame.stack[--current_frame.sp];current_frame.stack[current_frame.sp++]=(uint32_t)receiver;return 0;}
	if(!is_static&&matches(c,m,"java/lang/Object","getClass","()Ljava/lang/Class;")){uint64_t receiver=current_frame.stack[--current_frame.sp];const JVMR_Class *represented=jvmr_heap_object_class(receiver);return class_mirror_result(represented);}
	if(!is_static&&matches(c,m,"java/lang/reflect/Method","getName","()Ljava/lang/String;")){uint64_t receiver=current_frame.stack[--current_frame.sp];const JVMR_Method *method;if(jvmr_heap_method_mirror(receiver,NULL,&method))return -1;return push_host_string(method->name?method->name:"");}
	if(!is_static&&matches(c,m,"java/lang/reflect/Method","getModifiers","()I")){uint64_t receiver=current_frame.stack[--current_frame.sp];const JVMR_Method *method;if(jvmr_heap_method_mirror(receiver,NULL,&method))return -1;current_frame.stack[current_frame.sp++]=method->access_flags;return 0;}
	if(!is_static&&matches(c,m,"java/lang/reflect/Method","getParameterCount","()I")){uint64_t receiver=current_frame.stack[--current_frame.sp];const JVMR_Method *method;if(jvmr_heap_method_mirror(receiver,NULL,&method))return -1;current_frame.stack[current_frame.sp++]=(uint32_t)descriptor_count(method->descriptor);return 0;}
	if(!is_static&&matches(c,m,"java/lang/reflect/Method","getDeclaringClass","()Ljava/lang/Class;")){uint64_t receiver=current_frame.stack[--current_frame.sp];const JVMR_Class *declaring;if(jvmr_heap_method_mirror(receiver,&declaring,NULL))return -1;return class_mirror_result(declaring);}
	if(!is_static&&matches(c,m,"java/lang/reflect/Field","getName","()Ljava/lang/String;")){uint64_t receiver=current_frame.stack[--current_frame.sp];const JVMR_Field *field;if(jvmr_heap_field_mirror(receiver,NULL,&field))return -1;return push_host_string(field->name?field->name:"");}
	if(!is_static&&matches(c,m,"java/lang/reflect/Field","getModifiers","()I")){uint64_t receiver=current_frame.stack[--current_frame.sp];const JVMR_Field *field;if(jvmr_heap_field_mirror(receiver,NULL,&field))return -1;current_frame.stack[current_frame.sp++]=field->access_flags;return 0;}
	if(!is_static&&matches(c,m,"java/lang/reflect/Field","getDeclaringClass","()Ljava/lang/Class;")){uint64_t receiver=current_frame.stack[--current_frame.sp];const JVMR_Class *declaring;if(jvmr_heap_field_mirror(receiver,&declaring,NULL))return -1;return class_mirror_result(declaring);}
	if(!is_static&&matches(c,m,"java/lang/reflect/Field","get","(Ljava/lang/Object;)Ljava/lang/Object;")){uint64_t object=current_frame.stack[--current_frame.sp],mirror=current_frame.stack[--current_frame.sp];return reflected_field_value(mirror,object,0);}
	if(!is_static&&matches(c,m,"java/lang/reflect/Field","getInt","(Ljava/lang/Object;)I")){uint64_t object=current_frame.stack[--current_frame.sp],mirror=current_frame.stack[--current_frame.sp];return reflected_field_value(mirror,object,1);}
	if(!is_static&&matches(c,m,"java/lang/reflect/Method","invoke","(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;")){uint64_t argument_array=current_frame.stack[--current_frame.sp],object=current_frame.stack[--current_frame.sp],mirror=current_frame.stack[--current_frame.sp];return reflected_method_invoke(mirror,object,argument_array);}
	return 1;
}
